name: Publish Agent to GitHub Container Registry

on:
  workflow_dispatch:

env:
  GH_BRANCH: release
  DOCKER_TAG: latest

jobs:
  build_and_push_to_registry:

    name: Build image and publish to registry
    runs-on: ubuntu-latest

    steps:
#      - name: Checkout the rep
#        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image and push to GitHub Container Registry
        run: |
          docker build https://github.com/SpeedCurve-Metrics/wptagent.git#${GH_BRANCH} --tag ghcr.io/speedcurve-metrics/speedcurve-agent:${DOCKER_TAG}
          docker push ghcr.io/speedcurve-metrics/speedcurve-agent:${DOCKER_TAG}
